version: "3.8"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cms_db
      MYSQL_USER: oskari
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    environment:
      DB_HOST: mysql
      DB_USER: oskari
      DB_PASSWORD: password
      DB_NAME: cms_db
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    volumes:
      - ./backend:/usr/src/app

volumes:
  mysql_data:
